spring.application.name=DATN_PCGear_BackEnd
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pcgearhub;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=03102003
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
